### ISSUE TITLE
Apidoc-swagger crashes on apidoc specifications with custom parameter group names

### ISSUE THREAD

**Issue by brownstein** [fsbahman/apidoc-swagger#14] opened 2016-03-04 20:22 UTC
I'm using apidoc-swagger against a project which annotates URL parameters using a group named "URL Parameters" instead of the default, and I ran across some unsafe access patterns to the Parameters array.

Specifically,`var required = verbs.parameter && verbs.parameter.fields && verbs.parameter.fields.Parameter.length > 0;` on line 83 of apidocToSwagger.js makes an unsafe check, which causes an unhandled exception if "Parameter" is not defined.

PR incoming.

**Comment by bermi** [comment] 2016-07-30 13:37
Any chance of getting this merged? It seems to be the root cause for #19 as well.

**Comment by Vaxter** [comment] 2016-08-18 22:20
Fix proposed just skips handling everything if Parameters are not available resulting in not having parameters added in Swagger.
There was a proper fix for older version that was able to handle custom grouping, submitted by my friend and I, but pull request was not merged due to rewrite.

To fix this issue the right way, parameter grouping should be handled.

**Comment by brownstein** [comment] 2016-08-19 14:20
@Vaxter The alternative (current approach) seems to be to just crash, which also results in not having parameters added in Swagger. Not sure why this isn't a step in the right direction.

**Comment by Vaxter** [comment] 2016-09-13 11:03
@brownstein  https://github.com/fsbahman/apidoc-swagger/pull/25/commits/2d332e39a1a0847e1f39a1c6cc9c1b6f320fe9f1

Here, this is a step in the right direction.
Now fields are generated, but needs additional work to handle mixing groups and handling form data cases.
Also, apiDoc allows free form grouping, so better default group should also be handled.
This was a quick fix, but should do the trick.

**Closed as completed** 2018-09-06 21:20 UTC
